### PR TITLE
[FIX][189] Support :closing case in AMQP.Channel.open/2

### LINKED ISSUE #189: Application.Connection has a missing case clause on line 113
https://github.com/pma/amqp/blob/main/lib/amqp/application/channel.ex#L113

I'm not really sure how this should be resolved, but on our production app, we had a cascade failure where AMQP processes were often restarting and, among the several things we had issues with, one of them was that the line

https://github.com/pma/amqp/blob/main/lib/amqp/application/channel.ex#L113 

does not implement all the result clasuse. Apparently, one of the results could be

```
18:45:09.147 [error] Supervisor 'Elixir.AMQP.Application' had child 
'Elixir.AMQP.Application.Channel::producers'  started with 
'Elixir.AMQP.Application.Channel':start_link([{connection,mq_gate},{proc_name,producers}]) at <0.19215.77> 
exit with reason no case clause matching closing in 'Elixir.AMQP.Application.Channel':handle_info/2 line 113 
in context child_terminated    
```

```
@impl true
  def handle_info(:open, state) do
    case AMQP.Application.Connection.get_connection(state[:connection]) do
      {:ok, conn} ->
        case Channel.open(conn) do
          {:ok, chan} ->
            # ...
          {:error, error} ->
            # ...   
```

So it seems `Channel.open(conn)` can result in `:closing`, though is not apparent to me from the underlying erlang library. I would love to push a patch but I'm not sure what the appropriate way to handle it would be. Any pointers are welcome. I'm thinking same approach as with `{:error, error}` would work?

EDIT: Digging deep into the erlang library, it looks like `amqp_gen_connection.erl`

```erlang
open_channel(Pid, ProposedNumber, Consumer) ->
  case gen_server:call(Pid,
                       {command, {open_channel, ProposedNumber, Consumer}},
                       amqp_util:call_timeout()) of
      {ok, ChannelPid} -> ok = amqp_channel:open(ChannelPid),
                          {ok, ChannelPid};
      Error            -> Error
  end.
```

returns `{:ok, pid} | any`

While `deps/amqp_client/src/amqp_connection.erl`

defines the return for `open_channel/2` as `Result = {ok, ChannelPid} | {error, Error}`

So it seems there's a discrepancy there.

### PR DESCRIPTION
**Pull request by begedin**
Fixes #189 

Not sure this is the best approach, but I didn't want to affect how the existing tuple clause is handled (as it would change what is logged).

I also see `Basic.error` has a variant with a `:closing` atom in it, so I'm wondering if I should use that somehow.

Finally, I would love advice on how to write a test for this.

### CODE REVIEW

File: lib/amqp/application/channel.ex [hunk 1]
```diff
@@ -1,5 +1,6 @@
 defmodule AMQP.Application.Channel do
   @moduledoc false
+
```
Comment (begedin) [inline lib/amqp/application/channel.ex:3]: Formatter introduces this for me

File: lib/amqp/channel.ex [hunk 2]
```diff
@@ -17,7 +17,8 @@ defmodule AMQP.Channel do
   `:amqp_connection.open_channel/2` for more details and `AMQP.DirectConsumer` for an example of a
   custom consumer.
   """
-  @spec open(Connection.t(), custom_consumer | nil) :: {:ok, Channel.t()} | {:error, any}
+  @spec open(Connection.t(), custom_consumer | nil) ::
+          {:ok, Channel.t()} | {:error, any} | any
```
Comment (begedin) [inline lib/amqp/channel.ex:21]: Again, wanted to keep the tuple variant, just in case, but if the signature here needs to change, let me know.

**Comment by ono** [comment]
ah, it's a bug. instead of handling the case, we should return `{:error, :closing}` there.

Can you make a fix on https://github.com/pma/amqp/blob/main/lib/amqp/channel.ex#L39 and https://github.com/pma/amqp/blob/main/lib/amqp/channel.ex#L49 to ensure it return a tuple please? I will be adding a test case once it's merged too.

thanks for reporting!

File: lib/amqp/channel.ex [hunk 3]
```diff
@@ -45,8 +46,11 @@ defmodule AMQP.Channel do
       {:ok, chan_pid} ->
         {:ok, %Channel{conn: conn, pid: chan_pid, custom_consumer: custom_consumer}}
 
-      error ->
-        error
+      {:error, error} ->
+        {:error, error}
+
+      :closing ->
+        {:error, :closing}
```
Comment (begedin) [inline lib/amqp/channel.ex:53]: Not 100% sure what the policy in this repo is, but this way, we ensure we match only on tuple or closing atom, ensuring a tuple is returned.

If necessary, I can reintroduce the "catch all" error clause.

File: test/connection_test.exs [hunk 4]
```diff
@@ -59,7 +59,7 @@ defmodule ConnectionTest do
     assert :ok = Connection.close(conn)
   end
 
-  test "open connection with uri, name, and options (deprected but still spported)" do
+  test "open connection with uri, name, and options (deprected but still supported)" do
```
Comment (begedin) [inline test/connection_test.exs:62]: Had a deprecation message when running tests, so I noticed this and fixed.

File: lib/amqp/channel.ex (hunk 3 above)
Comment (begedin) [reply lib/amqp/channel.ex:53]: Is it possible to produce a test for this reliably, without mocks?

File: test/connection_test.exs [hunk 5]
```diff
@@ -59,7 +59,7 @@ defmodule ConnectionTest do
     assert :ok = Connection.close(conn)
   end
 
-  test "open connection with uri, name, and options (deprected but still spported)" do
+  test "open connection with uri, name, and options (deprecated but still supported)" do
```
Comment (ono) [inline test/connection_test.exs:62]: 🙇

File: lib/amqp/channel.ex (hunk 3 above)
Comment (ono) [reply lib/amqp/channel.ex:53]:
```elixir
error -> {:error, error}
```

should cover the case. like `close/1`.

I was thinking to pass a closed connection but not sure if it gives an error expected. if not, no worries about the test i can work out.

Comment (begedin) [reply lib/amqp/channel.ex]: Ah, sorry. I'm really bad at reading the underlying erlang code. I see what you mean now. I pushed another commit

**Comment by ono** [comment]
good stuff. thank you!
